### ISSUE TITLE
native-or-bluebird is deprecated. please switch to any-promise

### ISSUE THREAD

**Issue by jonathanong** [vdemedes/tempdir#1]
https://github.com/kevinbeaty/any-promise

this implementation supports more promise implementations and allows the end-user to configure the promise implementation.

**Comment by ashleygwilliams** [comment]
looks like this was solved by 2.0.0 https://github.com/vadimdemedes/tempdir/blob/master/package.json#L22

**Comment by vadimdemedes** [comment]
Yep, this module requires Node.js v4+ now.
